"""add_missing_fields_to_property

Revision ID: 2f3d8eb2b247
Revises: 34dd6fcb6575
Create Date: 2026-01-17 21:05:33.946885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3d8eb2b247'
down_revision: Union[str, Sequence[str], None] = '34dd6fcb6575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
