"""add_missing_fields_to_property

Revision ID: 34dd6fcb6575
Revises: 516b453f2beb
Create Date: 2026-01-17 21:02:20.528455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dd6fcb6575'
down_revision: Union[str, Sequence[str], None] = '516b453f2beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('distances', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('complex_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('district', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('badges', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('investment_metrics', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('growth_forecasts', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('development_projects', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('eco_score', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('green_zones', sa.JSON(), nullable=False))
    op.add_column('properties', sa.Column('owner_quote', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('agent_profile', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'agent_profile')
    op.drop_column('properties', 'owner_name')
    op.drop_column('properties', 'owner_quote')
    op.drop_column('properties', 'green_zones')
    op.drop_column('properties', 'eco_score')
    op.drop_column('properties', 'development_projects')
    op.drop_column('properties', 'growth_forecasts')
    op.drop_column('properties', 'investment_metrics')
    op.drop_column('properties', 'badges')
    op.drop_column('properties', 'district')
    op.drop_column('properties', 'complex_name')
    op.drop_column('properties', 'quality_score')
    op.drop_column('properties', 'distances')
    # ### end Alembic commands ###
